all: # keys must be unique, i.e. only one 'hosts' per group
    hosts:
        127.0.0.1
    vars:
        docker_compose_home: "/apps/larasite"
        app_user: ubuntu
        app_group: ubuntu
        # 靠环境变量传递
        # lavavel_zip_path: ''
        # app_home: ""