all:
  children:
    webservers:
      hosts:
        34.230.3.87
      vars:
        ansible_ssh_private_key_file: /Users/jack/Downloads/larasite.pem
        ansible_ssh_user: admin
        docker_compose_home: "/apps/larasite"
        app_user: admin
        app_group: admin
        # 靠环境变量传递
        # lavavel_zip_path: ''
        app_home: ""
        db_root_password: "mysql"
        laravel_app_env:
          APP_NAME: app
          APP_ENV: production
          APP_KEY: base64:ZXFpM2hwaTZubGhuMzBrOHlzZTA5OTBsMnkwY3R0dWw=
          APP_DEBUG: false
          APP_URL: https://app.com/
          LOG_CHANNEL: stack
          LOG_DEPRECATIONS_CHANNEL: 
          LOG_LEVEL: debug
          DB_CONNECTION: mysql
          DB_DATABASE: forge
          DB_HOST: db
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: "{{ db_root_password }}"
          BROADCAST_DRIVER: log
          CACHE_DRIVER: file
          FILESYSTEM_DRIVER: local
          QUEUE_CONNECTION: 
          SESSION_DRIVER: file
          SESSION_LIFETIME: 120
          MEMCACHED_HOST: 
          REDIS_HOST: 
          REDIS_PASSWORD: 
          REDIS_PORT: 
          MAIL_MAILER: 
          MAIL_HOST: 
          MAIL_PORT: 
          MAIL_USERNAME: 
          MAIL_PASSWORD: 
          MAIL_ENCRYPTION: 
          MAIL_FROM_ADDRESS: 
          MAIL_FROM_NAME: 
          AWS_ACCESS_KEY_ID: 
          AWS_SECRET_ACCESS_KEY: 
          AWS_DEFAULT_REGION: 
          AWS_BUCKET: 
          AWS_USE_PATH_STYLE_ENDPOINT: 
          PUSHER_APP_ID: 
          PUSHER_APP_KEY: 
          PUSHER_APP_SECRET: 
          PUSHER_APP_CLUSTER: 
          MIX_PUSHER_APP_KEY: 
          MIX_PUSHER_APP_CLUSTER: 
          WEIXINWEB_CLIENT_ID: 
          WEIXINWEB_CLIENT_SECRET: 
          WEIXINWEB_REDIRECT_URI: 
          ADMIN_USER_EMAIL: 
          ADMIN_USER_PASSWORD: 
          FIREBASE_CREDENTIALS: resources/credentials/firebase_credentials.json
