---
# defaults file for larasite
lara_docker_compose:
  version: '3'
  services:
    myapp:
      image: docker.io/bitnami/laravel:8
      # container_name: prod_myapp
      mem_limit: 800M
      mem_reservation: 128M
      cpus: 0.8
      restart: "always"
      ports:
        - '8888:8000'
      volumes:
        - '{{app_home}}/:/app'
      # extra_hosts:
      #   - "host.docker.internal:host-gateway"
laravel_app_env:
  APP_NAME:
  APP_ENV:
  APP_KEY:
  APP_DEBUG:
  APP_URL:
  LOG_CHANNEL:
  LOG_DEPRECATIONS_CHANNEL:
  LOG_LEVEL:
  DB_CONNECTION:
  DB_DATABASE:
  DB_HOST:
  DB_PORT:
  DB_USERNAME:
  DB_PASSWORD:
  BROADCAST_DRIVER:
  CACHE_DRIVER:
  FILESYSTEM_DRIVER:
  QUEUE_CONNECTION:
  SESSION_DRIVER:
  SESSION_LIFETIME:
  MEMCACHED_HOST:
  REDIS_HOST:
  REDIS_PASSWORD: null
  REDIS_PORT: 6379
  MAIL_MAILER:
  MAIL_HOST:
  MAIL_PORT:
  MAIL_USERNAME:
  MAIL_PASSWORD:
  MAIL_ENCRYPTION:
  MAIL_FROM_ADDRESS:
  MAIL_FROM_NAME:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  AWS_BUCKET:
  AWS_USE_PATH_STYLE_ENDPOINT:
  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER:
  MIX_PUSHER_APP_KEY:
  MIX_PUSHER_APP_CLUSTER:
  WEIXINWEB_CLIENT_ID:
  WEIXINWEB_CLIENT_SECRET:
  WEIXINWEB_REDIRECT_URI:
  ADMIN_USER_EMAIL:
  ADMIN_USER_PASSWORD:
  FIREBASE_CREDENTIALS: resources/credentials/firebase_credentials.json
