name: Production deployment
on:
  release:
    types: [prereleased, released]

env:
  PROD_LIGHTSAIL_DEFAULT_KEY: ${{ secrets.PROD_LIGHTSAIL_DEFAULT_KEY }}
  PROD_LIGHTSAIL_HOST_IP: ${{ secrets.PROD_LIGHTSAIL_HOST_IP }}

jobs:
  release:
    name: ${{ github.event.release.tag_name }} to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: download laravel.zip
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          version: "${{ github.event.release.id }}"
          file: 'laravel.zip'
          target: '${GITHUB_WORKSPACE}/laravel.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: run ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          # Optional, directory where playbooks live
          directory: ./devops
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory prod.hosts.yaml
            --extra-vars lavavel_zip_path=${GITHUB_WORKSPACE}/laravel.zip
          
