name: Production deployment
on:
  release:
    types: [prereleased, released]

env:
  PROD_LIGHTSAIL_DEFAULT_KEY: ${{ secrets.PROD_LIGHTSAIL_DEFAULT_KEY }}
  PROD_LIGHTSAIL_HOST_IP: ${{ secrets.PROD_LIGHTSAIL_HOST_IP }}
  ARTIFACT_VERSION: "${{github.event.release.tag_name}}"
  ARTIFACT_NAME: laravel-${{github.event.release.tag_name}}.zip
  DEVOPS_ANSIBLE_NAME: devops-${{github.event.release.tag_name}}.zip

jobs:
  release:
    name: ${{ github.event.release.tag_name }} to production
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.event.release.tag_name }}

      - name: download laravel.zip
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          version: "${{ github.event.release.id }}"
          file: '${{env.ARTIFACT_NAME}}'
          target: '${GITHUB_WORKSPACE}/${{env.ARTIFACT_NAME}}'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: download devops.zip
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          version: "${{ github.event.release.id }}"
          file: '${{ env.DEVOPS_ANSIBLE_NAME }}'
          target: '${GITHUB_WORKSPACE}/${{ env.DEVOPS_ANSIBLE_NAME }}'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${GITHUB_WORKSPACE}/${{ env.DEVOPS_ANSIBLE_NAME }} -d devops

      - name: deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          # Optional, directory where playbooks live
          directory: ${GITHUB_WORKSPACE}/devops
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory prod.hosts.yaml
            --extra-vars lavavel_zip_path=${GITHUB_WORKSPACE}/${{env.ARTIFACT_NAME}} docker_compose_home="/apps/larasite" app_home="/apps/larasite/${{env.ARTIFACT_VERSION}}"
          
