---
- name: mkdir folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_group}}"
    mode: u=rw,g=r,o=r
    loop:
      - "{{ docker_compose_home }}"
      - "{{ app_home }}"

- name: copy laravel.zip
  ansible.builtin.copy:
    src: "{{ lavavel_zip_path }}"
    dest: "{{ app_home }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: u=rw,g=r,o=r

- name: extract laravel
  ansible.builtin.unarchive:
    src: "{{ lavavel_zip_path }}"
    dest: "{{ app_home }}"


# tasks file for larasite
- name: template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{docker_compose_home}}/docker-compose.yaml"
    owner: "{{app_user}}"
    group: "{{app_group}}"
    mode: u=rw,g=r,o=r

- name: start services
  docker_compose:
    project_src: "{{docker_compose_home}}"
  register: output

- debug:
    var: output
